### ISSUE TITLE
Как использовать видеокарту, а не процессор? 

### ISSUE THREAD

**Issue by IVIiracle** [davabase/whisper_real_time#35]
Почему-то не могу никак понять, как именно и где прописать, чтобы whisper использовал мощности моей видеокарты, а лучше совмещать мог ее и процессор? Ибо какой толк использовать лишь его? Кто знает - поделитесь.

**Comment by davabase** [comment]
Вы должны установить версию PyTorch для CUDA, инструкции можно найти на этой странице:
https://pytorch.org/get-started/locally/
```
pip3 install torch --index-url https://download.pytorch.org/whl/cu117
```

Затем вы можете проверить, поддерживает ли ваш компьютер использование Torch на GPU, выполнив эту команду в вашем терминале:
```
python -c "import torch; print(torch.cuda.is_available())"
```
Она должна вывести True; если выводится False, что-то идет не так. Попробуйте удалить PyTorch с помощью следующей команды:
```
pip uninstall torch
```
и затем переустановить его. Если это не помогло, то, к сожалению, ваш компьютер, возможно, не поддерживает CUDA, и вам может потребоваться обновить драйверы NVIDIA.


----
You must install the CUDA version of pytorch you can see the instructions on this page:
https://pytorch.org/get-started/locally/
```
pip3 install torch --index-url https://download.pytorch.org/whl/cu117
```

You can then check that your computer supports torch on the GPU by running this command in your terminal:
```
python -c "import torch; print(torch.cuda.is_available())"
```
It should print True, if it prints False something is wrong. Try uninstalling pytorch with:
```
pip uninstall torch
```
and reinstalling it. If that doesn't work then I'm afraid your computer doesn't support CUDA, you may have to update your NVIDIA drivers.

**Comment by IVIiracle** [comment]
> Вы должны установить версию PyTorch для CUDA, инструкции можно найти на этой странице...

Спасибо большое, все заработало.
